import { ProductCatalogItem } from "../../model/genie/genieModels";

export const PRODUCT_CATALOG: ProductCatalogItem[] = [
  {
    id: "genie-hydra-cloud",
    productName: "Hydra Cloud Barrier Cream",
    brand: "Genie Labs",
    category: "Skincare",
    subcategory: "Moisturizer",
    description: "A cushiony moisturizer designed to hydrate dry and sensitive skin without feeling heavy.",
    imageUrl: "https://media.ulta.com/i/ulta/2564751",
    productUrl: "https://www.ulta.com/",
    price: 42,
    originalPrice: 48,
    currency: "USD",
    skinTypes: ["dry", "sensitive", "combination"],
    concerns: ["dehydration", "barrier support", "redness"],
    preferences: ["hydrating", "dewy", "fragrance-free"],
    finish: "dewy",
    keyIngredient: "Hyaluronic acid",
    badges: ["Top Pick", "Barrier Support"],
    tags: ["Dry skin", "Sensitive-safe", "Dewy finish"],
    rating: 4.8,
    reviewCount: 2140,
  },
  {
    id: "genie-gentle-cleanse",
    productName: "Calm Reset Cream Cleanser",
    brand: "Pure Current",
    category: "Skincare",
    subcategory: "Cleanser",
    description: "A non-stripping cream cleanser that removes makeup and helps reduce post-cleanse tightness.",
    imageUrl: "https://media.ulta.com/i/ulta/2536676",
    productUrl: "https://www.ulta.com/",
    price: 24,
    originalPrice: 24,
    currency: "USD",
    skinTypes: ["dry", "sensitive", "normal"],
    concerns: ["sensitivity", "redness", "dehydration"],
    preferences: ["fragrance-free", "gentle"],
    finish: "natural",
    keyIngredient: "Ceramides",
    badges: ["Derm Favorite"],
    tags: ["Gentle cleanse", "Barrier care"],
    rating: 4.6,
    reviewCount: 1208,
  },
  {
    id: "genie-matte-balance",
    productName: "Balance Blur Soft Matte Foundation",
    brand: "Studio Hue",
    category: "Makeup",
    subcategory: "Foundation",
    description: "A medium-coverage foundation that helps control shine while keeping texture smooth.",
    imageUrl: "https://media.ulta.com/i/ulta/2610673",
    productUrl: "https://www.ulta.com/",
    price: 35,
    originalPrice: 39,
    currency: "USD",
    skinTypes: ["oily", "combination"],
    concerns: ["shine", "texture", "pores"],
    preferences: ["matte", "longwear"],
    finish: "matte",
    keyIngredient: "Niacinamide",
    badges: ["Best Seller"],
    tags: ["Oil control", "Longwear"],
    rating: 4.5,
    reviewCount: 6430,
  },
  {
    id: "genie-radiance-serum",
    productName: "Radiance Reset Vitamin C Serum",
    brand: "Bright Theory",
    category: "Skincare",
    subcategory: "Serum",
    description: "A brightening serum formulated to target dullness and the look of dark spots.",
    imageUrl: "https://media.ulta.com/i/ulta/2603465",
    productUrl: "https://www.ulta.com/",
    price: 38,
    originalPrice: 44,
    currency: "USD",
    skinTypes: ["normal", "dry", "combination"],
    concerns: ["dark spots", "dullness", "uneven tone"],
    preferences: ["brightening", "lightweight"],
    finish: "natural",
    keyIngredient: "Vitamin C",
    badges: ["Brightening"],
    tags: ["Dark spot care", "Glow support"],
    rating: 4.7,
    reviewCount: 3189,
  },
  {
    id: "genie-calm-spf",
    productName: "Daily Calm Mineral SPF 30",
    brand: "Genie Labs",
    category: "Skincare",
    subcategory: "Sunscreen",
    description: "A lightweight mineral sunscreen with a comfortable finish for sensitive and redness-prone skin.",
    imageUrl: "https://media.ulta.com/i/ulta/2610861",
    productUrl: "https://www.ulta.com/",
    price: 29,
    originalPrice: 32,
    currency: "USD",
    skinTypes: ["sensitive", "normal", "combination"],
    concerns: ["sun protection", "redness"],
    preferences: ["lightweight", "mineral", "fragrance-free"],
    finish: "natural",
    keyIngredient: "Zinc oxide",
    badges: ["Daily Essential"],
    tags: ["Mineral SPF", "Sensitive-safe"],
    rating: 4.4,
    reviewCount: 1675,
  },
  {
    id: "genie-night-renewal",
    productName: "Overnight Renewal Retinol Serum",
    brand: "Clinical Edit",
    category: "Skincare",
    subcategory: "Treatment",
    description: "A beginner-friendly retinol serum aimed at smoothing fine lines and refining uneven texture.",
    imageUrl: "https://media.ulta.com/i/ulta/2587487",
    productUrl: "https://www.ulta.com/",
    price: 46,
    originalPrice: 52,
    currency: "USD",
    skinTypes: ["normal", "combination", "oily"],
    concerns: ["fine lines", "texture", "aging"],
    preferences: ["anti-aging", "lightweight"],
    finish: "natural",
    keyIngredient: "Retinol",
    badges: ["Editor Pick"],
    tags: ["Night treatment", "Smoothing"],
    rating: 4.3,
    reviewCount: 2894,
  },
  {
    id: "genie-dewy-skin-tint",
    productName: "Luminous Flex Skin Tint",
    brand: "Studio Hue",
    category: "Makeup",
    subcategory: "Skin Tint",
    description: "A light-coverage skin tint that adds glow and evens tone for a fresh finish.",
    imageUrl: "https://media.ulta.com/i/ulta/2615288",
    productUrl: "https://www.ulta.com/",
    price: 32,
    originalPrice: 32,
    currency: "USD",
    skinTypes: ["dry", "normal", "combination"],
    concerns: ["dullness", "uneven tone"],
    preferences: ["dewy", "lightweight", "natural makeup"],
    finish: "dewy",
    keyIngredient: "Squalane",
    badges: ["Glow Favorite"],
    tags: ["Sheer coverage", "Radiant look"],
    rating: 4.7,
    reviewCount: 4051,
  },
  {
    id: "genie-clarify-gel",
    productName: "Clarify Clear Gel Moisturizer",
    brand: "Pure Current",
    category: "Skincare",
    subcategory: "Moisturizer",
    description: "An oil-free gel moisturizer that hydrates while helping reduce midday shine.",
    imageUrl: "https://media.ulta.com/i/ulta/2263467",
    productUrl: "https://www.ulta.com/",
    price: 27,
    originalPrice: 30,
    currency: "USD",
    skinTypes: ["oily", "combination"],
    concerns: ["shine", "acne", "texture"],
    preferences: ["oil-free", "lightweight", "matte"],
    finish: "matte",
    keyIngredient: "Salicylic acid",
    badges: ["Oil Control"],
    tags: ["Acne-friendly", "Gel texture"],
    rating: 4.2,
    reviewCount: 1988,
  },
];
