import { ProductCatalogItem } from "../../model/genie/genieModels";

export const PRODUCT_CATALOG: ProductCatalogItem[] = [
  {
    id: "schick-hydro-sensitive-5",
    productName: "Hydro Sensitive 5 Razor",
    brand: "Schick",
    category: "Razors",
    subcategory: "Cartridge Razor",
    description: "Premium cartridge system built for a close shave with comfort cues that help sellers justify trade-up.",
    imageUrl: "https://placehold.co/600x600/e8f0f7/1f3b5b.png?text=Schick+Hydro+Sensitive+5",
    productUrl: "https://example.com/edgewell-sales-genie/catalog/schick-hydro-sensitive-5",
    price: 13,
    originalPrice: 15,
    currency: "USD",
    skinTypes: ["sensitive", "normal", "combination"],
    concerns: ["sensitive skin", "premium shave", "competitive positioning", "trade-up", "basket building"],
    preferences: ["walmart", "target", "premium", "performance", "buyer pitch"],
    finish: "natural",
    keyIngredient: "Shock-absorb gel pools",
    keyBenefits: ["Premium comfort", "Close shave", "Trade-up story"],
    competitivePositioning: "Wins when the retailer needs a premium cartridge option that balances performance and value against Gillette.",
    retailerContext: ["Walmart", "Target", "Drug", "Mass"],
    bundleIdeas: ["Pair with Edge Sensitive shave gel", "Bundle with refill blades for higher basket ring"],
    talkingPoints: ["Premium shave without overreaching on price", "Sensitive-skin comfort cues are easy for buyers to understand", "Strong fit for men’s grooming trade-up sets"],
    objectionHandling: ["If price comes up, position it as a value-premium option below top-tier Gillette systems", "If space is tight, lead with its role as the premium step-up inside the Schick lineup"],
    seasonality: ["Father's Day", "Holiday gifting", "Everyday core"],
    suggestedPitch: "Hydro Sensitive 5 gives Walmart and Target a premium Schick story with a clear step-up from value disposables.",
    badges: ["Trade-Up Driver", "Core Assortment"],
    tags: ["Premium shave", "Sensitive comfort", "Mass retail"],
    rating: 4.8,
    reviewCount: 1824,
  },
  {
    id: "schick-xtreme3-sensitive",
    productName: "Xtreme 3 Sensitive Disposable Razors",
    brand: "Schick",
    category: "Razors",
    subcategory: "Disposable Razor",
    description: "Value-oriented disposable pack that supports volume merchandising and convenience-led sell-in.",
    imageUrl: "https://placehold.co/600x600/e8f0f7/1f3b5b.png?text=Schick+Xtreme+3+Sensitive",
    productUrl: "https://example.com/edgewell-sales-genie/catalog/schick-xtreme3-sensitive",
    price: 8,
    originalPrice: 9,
    currency: "USD",
    skinTypes: ["sensitive", "normal"],
    concerns: ["value shave", "back-to-school", "travel", "impulse", "competitive positioning"],
    preferences: ["walmart", "club", "value", "front end", "seasonal"],
    finish: "matte",
    keyIngredient: "Flexible 3-blade head",
    keyBenefits: ["Accessible price", "Trusted performance", "Easy stock-up"],
    competitivePositioning: "Wins versus private label and lower-tier disposables when the buyer wants known-brand value without stretching shelf price.",
    retailerContext: ["Walmart", "Dollar", "Club", "Convenience"],
    bundleIdeas: ["Back-to-school grooming bundle with Wet Ones", "Travel shave set with Edge shave gel"],
    talkingPoints: ["Known-brand value for high-turn doors", "Good fit for temporary displays and endcaps", "Simple story for family stock-up trips"],
    objectionHandling: ["If the buyer sees it as entry tier, reinforce that the Schick name still signals trust and repeat purchase", "If they want margin, position multi-pack velocity and seasonal display flexibility"],
    seasonality: ["Back-to-school", "Spring reset", "Travel season"],
    suggestedPitch: "Xtreme 3 Sensitive is an easy yes for value retailers that need branded disposable velocity during travel and back-to-school periods.",
    badges: ["Value Leader", "Display Friendly"],
    tags: ["Disposable", "Value", "Seasonal"],
    rating: 4.5,
    reviewCount: 2410,
  },
  {
    id: "wilkinson-intuition-complete",
    productName: "Intuition Complete Razor Kit",
    brand: "Wilkinson Sword",
    category: "Razors",
    subcategory: "Women's Razor",
    description: "All-in-one women’s shave system with convenience cues that help broaden the Edgewell shave story.",
    imageUrl: "https://placehold.co/600x600/f7eadf/6b4a2b.png?text=Wilkinson+Intuition+Complete",
    productUrl: "https://example.com/edgewell-sales-genie/catalog/wilkinson-intuition-complete",
    price: 14,
    originalPrice: 16,
    currency: "USD",
    skinTypes: ["sensitive", "normal", "dry"],
    concerns: ["women's grooming", "convenience", "trade-up", "giftable", "bundle"],
    preferences: ["target", "drug", "premium", "self-care", "buyer pitch"],
    finish: "dewy",
    keyIngredient: "Built-in skin-conditioning bar",
    keyBenefits: ["Convenience", "No separate shave prep required", "Premium feminine grooming"],
    competitivePositioning: "Wins when the buyer wants a more complete and convenient women’s shave system versus basic disposable sets.",
    retailerContext: ["Target", "Drug", "Grocery"],
    bundleIdeas: ["Pair with Skintimate shave prep", "Cross-merchandise with Bulldog or Jack Black gifting during holiday sets"],
    talkingPoints: ["Convenience-led shave system", "Easy premium step-up for women’s grooming", "Supports self-care and gifting stories"],
    objectionHandling: ["If the buyer worries about duplication, position it as a distinct convenience choice rather than a basic razor replacement", "If price is the concern, emphasize reduced need for separate prep on first trial"],
    seasonality: ["Holiday gifting", "Mother's Day", "Spring refresh"],
    suggestedPitch: "Intuition Complete helps Target and drug accounts tell a more elevated women’s shave story with strong convenience cues.",
    badges: ["Convenience Story", "Premium Women's"],
    tags: ["Women's shave", "Trade-up", "Giftable"],
    rating: 4.6,
    reviewCount: 968,
  },
  {
    id: "personna-caliber-5-refills",
    productName: "Caliber 5 Razor Blade Refills",
    brand: "Personna",
    category: "Razors",
    subcategory: "Refill Blades",
    description: "Refill pack that extends the shave system story and gives retailers a clear repeat-purchase component.",
    imageUrl: "https://placehold.co/600x600/eceff4/3f4854.png?text=Personna+Caliber+5+Refills",
    productUrl: "https://example.com/edgewell-sales-genie/catalog/personna-caliber-5-refills",
    price: 16,
    originalPrice: 18,
    currency: "USD",
    skinTypes: ["normal", "combination"],
    concerns: ["refill", "repeat purchase", "margin mix", "basket building"],
    preferences: ["club", "mass", "value-premium", "everyday core"],
    finish: "natural",
    keyIngredient: "Five-blade refill format",
    keyBenefits: ["Repeat purchase", "Loyalty driver", "Good price-pack architecture"],
    competitivePositioning: "Wins when the account needs refill economics and a strong attach story rather than single-purchase disposables.",
    retailerContext: ["Club", "Mass", "Drug"],
    bundleIdeas: ["Merchandise beside core shave systems", "Bundle with Edge shave prep to lift total shave basket"],
    talkingPoints: ["Supports repeat trips", "Improves the lifetime value story of the razor aisle", "Useful for accounts that want refill depth"],
    objectionHandling: ["If the buyer wants simpler assortment, pitch it as the repeat-purchase companion to a focused system set", "If they compare on velocity, lead with refill-driven shopper retention"],
    seasonality: ["Everyday core", "Holiday stock-up"],
    suggestedPitch: "Caliber 5 refills give the shelf a repeat-purchase engine and a clearer razor system architecture.",
    badges: ["Repeat Purchase", "Margin Mix"],
    tags: ["Refills", "Attach rate", "Core"],
    rating: 4.4,
    reviewCount: 721,
  },
  {
    id: "edge-ultra-sensitive-gel",
    productName: "Ultra Sensitive Shave Gel",
    brand: "Edge",
    category: "Shave Prep",
    subcategory: "Shave Gel",
    description: "Sensitive-skin shave prep that pairs naturally with Schick systems and strengthens the total shave solution story.",
    imageUrl: "https://placehold.co/600x600/e4f6f1/215a4c.png?text=Edge+Ultra+Sensitive+Gel",
    productUrl: "https://example.com/edgewell-sales-genie/catalog/edge-ultra-sensitive-gel",
    price: 4,
    originalPrice: 5,
    currency: "USD",
    skinTypes: ["sensitive", "normal"],
    concerns: ["sensitive skin", "bundle", "basket building", "shave prep", "competitive positioning"],
    preferences: ["walmart", "grocery", "mass", "value", "cross-merchandising"],
    finish: "natural",
    keyIngredient: "Aloe and conditioning lubricants",
    keyBenefits: ["Low-barrier add-on", "Cross-sell companion", "Sensitive comfort story"],
    competitivePositioning: "Wins by giving retailers an affordable branded prep option that strengthens the shave basket against private label.",
    retailerContext: ["Walmart", "Grocery", "Mass"],
    bundleIdeas: ["Bundle with Hydro Sensitive 5", "Add to men’s grooming event packs"],
    talkingPoints: ["Easy attach item", "Supports better shave experience messaging", "Affordable way to grow basket size"],
    objectionHandling: ["If space is limited, frame it as a high-attachment SKU that supports the core razor system", "If value is questioned, position it as the simplest way to add dollars to the shave aisle"],
    seasonality: ["Father's Day", "Holiday gifting", "Everyday core"],
    suggestedPitch: "Edge Ultra Sensitive is the attach item that turns a razor sale into a total shave solution.",
    badges: ["Bundle Driver", "Low Price Add-On"],
    tags: ["Shave prep", "Attach item", "Sensitive"],
    rating: 4.7,
    reviewCount: 2050,
  },
  {
    id: "skintimate-skin-therapy",
    productName: "Skin Therapy Moisturizing Shave Gel",
    brand: "Skintimate",
    category: "Shave Prep",
    subcategory: "Women's Shave Gel",
    description: "Women’s shave prep built for moisture messaging, easy pairing, and seasonal self-care promotions.",
    imageUrl: "https://placehold.co/600x600/f8e7ee/8b4960.png?text=Skintimate+Skin+Therapy",
    productUrl: "https://example.com/edgewell-sales-genie/catalog/skintimate-skin-therapy",
    price: 4,
    originalPrice: 5,
    currency: "USD",
    skinTypes: ["dry", "normal", "sensitive"],
    concerns: ["women's grooming", "bundle", "moisture", "self-care", "seasonal promotion"],
    preferences: ["target", "drug", "self-care", "bundle", "spring"],
    finish: "dewy",
    keyIngredient: "Vitamin E and moisturizers",
    keyBenefits: ["Moisture-led story", "Strong pairing item", "Accessible self-care add-on"],
    competitivePositioning: "Wins by giving the women’s shave set a more complete and more sensory proposition than a bare razor-only assortment.",
    retailerContext: ["Target", "Drug", "Grocery"],
    bundleIdeas: ["Pair with Intuition Complete", "Use in spring self-care or Mother’s Day feature sets"],
    talkingPoints: ["Improves the women’s shave basket", "Supports self-care storytelling without premium pricing", "Easy seasonal event item"],
    objectionHandling: ["If the buyer views it as duplicative, show how it expands the women’s shave routine instead of replacing a razor SKU", "If they want stronger turns, propose it as a display pair with Intuition"],
    seasonality: ["Spring refresh", "Mother's Day", "Holiday gifting"],
    suggestedPitch: "Skintimate Skin Therapy helps retailers round out women’s shave with a low-cost, moisture-led companion item.",
    badges: ["Self-Care Story", "Women's Bundle"],
    tags: ["Women's shave", "Moisture", "Seasonal"],
    rating: 4.5,
    reviewCount: 1492,
  },
  {
    id: "banana-boat-sport-ultra-spf50",
    productName: "Sport Ultra SPF 50 Lotion",
    brand: "Banana Boat",
    category: "Sun Care",
    subcategory: "Sunscreen Lotion",
    description: "High-velocity sport sunscreen built for summer displays, family travel, and outdoor-event storytelling.",
    imageUrl: "https://placehold.co/600x600/fff0d8/9d6b18.png?text=Banana+Boat+Sport+Ultra+SPF+50",
    productUrl: "https://example.com/edgewell-sales-genie/catalog/banana-boat-sport-ultra-spf50",
    price: 10,
    originalPrice: 12,
    currency: "USD",
    skinTypes: ["normal", "sensitive"],
    concerns: ["summer promotion", "family protection", "outdoor activity", "display", "competitive positioning"],
    preferences: ["walmart", "grocery", "mass", "summer", "endcap"],
    finish: "natural",
    keyIngredient: "Broad-spectrum UVA/UVB filters",
    keyBenefits: ["Trusted family protection", "Strong seasonal velocity", "Event-ready display item"],
    competitivePositioning: "Wins versus premium-priced sport sun care when the buyer wants proven SPF authority and high-turn summer value.",
    retailerContext: ["Walmart", "Grocery", "Mass", "Club"],
    bundleIdeas: ["Pair with Wet Ones for family travel kits", "Build a summer endcap with Hawaiian Tropic for sport plus lifestyle coverage"],
    talkingPoints: ["Strong summer traffic driver", "Easy family protection story", "Fits endcaps, seasonal shippers, and travel sets"],
    objectionHandling: ["If the buyer asks about differentiation, lead with trusted SPF equity and accessible price points", "If shelf space is constrained, pitch it as one of the highest-utility summer essentials"],
    seasonality: ["Memorial Day", "Summer", "Back-to-school sports"],
    suggestedPitch: "Banana Boat Sport Ultra is the dependable summer workhorse for Walmart, grocery, and mass outdoor sets.",
    badges: ["Summer Driver", "Family Essential"],
    tags: ["Sun care", "Summer", "Outdoor"],
    rating: 4.9,
    reviewCount: 5321,
  },
  {
    id: "hawaiian-tropic-sheer-touch-spf30",
    productName: "Sheer Touch SPF 30 Lotion",
    brand: "Hawaiian Tropic",
    category: "Sun Care",
    subcategory: "Sunscreen Lotion",
    description: "Lifestyle-led sun care option that supports premium scent and sensorial storytelling during peak summer selling.",
    imageUrl: "https://placehold.co/600x600/ffe3cf/8c4d2d.png?text=Hawaiian+Tropic+Sheer+Touch+SPF+30",
    productUrl: "https://example.com/edgewell-sales-genie/catalog/hawaiian-tropic-sheer-touch-spf30",
    price: 11,
    originalPrice: 13,
    currency: "USD",
    skinTypes: ["normal", "dry"],
    concerns: ["summer promotion", "premium scent", "lifestyle sun care", "trade-up"],
    preferences: ["target", "drug", "premium", "summer", "lifestyle-led"],
    finish: "dewy",
    keyIngredient: "Coconut and island-inspired moisturizers",
    keyBenefits: ["Premium sensorial story", "Lifestyle positioning", "Trade-up within sun care"],
    competitivePositioning: "Wins when the retailer wants to add a more indulgent sun care option next to sport-driven protection items.",
    retailerContext: ["Target", "Drug", "Mass"],
    bundleIdeas: ["Merchandise alongside Banana Boat for good-better assortment", "Use in vacation and beach-trip displays"],
    talkingPoints: ["Adds emotion to the sun care shelf", "Creates a clear premium step-up", "Balances protection with experience"],
    objectionHandling: ["If the buyer sees it as niche, frame it as the lifestyle complement to sport SPF", "If price is questioned, lead with premium trade-up and differentiated shopper appeal"],
    seasonality: ["Spring break", "Summer", "Vacation travel"],
    suggestedPitch: "Hawaiian Tropic Sheer Touch gives Target and drug buyers a premium, sensorial step-up inside the summer set.",
    badges: ["Premium Sun", "Trade-Up"],
    tags: ["Sun care", "Lifestyle", "Premium"],
    rating: 4.6,
    reviewCount: 2876,
  },
  {
    id: "wet-ones-travel-pack",
    productName: "Antibacterial Hand Wipes Travel Pack",
    brand: "Wet Ones",
    category: "Hygiene",
    subcategory: "Wipes",
    description: "Portable hygiene essential with strong checkout, travel, and school-season utility.",
    imageUrl: "https://placehold.co/600x600/e9f5ff/2a5674.png?text=Wet+Ones+Travel+Pack",
    productUrl: "https://example.com/edgewell-sales-genie/catalog/wet-ones-travel-pack",
    price: 3,
    originalPrice: 4,
    currency: "USD",
    skinTypes: ["sensitive", "normal"],
    concerns: ["back-to-school", "travel", "checkout", "impulse", "hygiene"],
    preferences: ["walmart", "target", "convenience", "front end", "seasonal"],
    finish: "matte",
    keyIngredient: "Antibacterial wipe format",
    keyBenefits: ["Portable hygiene", "Impulse-ready", "Multi-season utility"],
    competitivePositioning: "Wins by combining trusted hygiene equity with a portable format that works across front-end and seasonal placements.",
    retailerContext: ["Walmart", "Target", "Convenience", "Drug"],
    bundleIdeas: ["Back-to-school hygiene bundle with Schick disposables", "Travel essentials clip-strip with Banana Boat travel sun care"],
    talkingPoints: ["Easy front-end story", "Works across school, travel, and cold/flu periods", "Broad household relevance"],
    objectionHandling: ["If the buyer sees it as commoditized, emphasize branded trust and flexible placement options", "If space is limited, pitch secondary placement near checkout or travel"],
    seasonality: ["Back-to-school", "Travel season", "Cold and flu"],
    suggestedPitch: "Wet Ones Travel Pack is a low-price, high-relevance item that belongs in back-to-school and travel adjacency.",
    badges: ["Impulse Driver", "Seasonal Utility"],
    tags: ["Hygiene", "Travel", "Front end"],
    rating: 4.8,
    reviewCount: 4108,
  },
  {
    id: "cremo-cooling-shave-cream",
    productName: "Cooling Shave Cream",
    brand: "Cremo",
    category: "Grooming",
    subcategory: "Shave Cream",
    description: "Performance-led grooming item that helps elevate the men’s shelf with a premium preparation story.",
    imageUrl: "https://placehold.co/600x600/eaf4ef/355a44.png?text=Cremo+Cooling+Shave+Cream",
    productUrl: "https://example.com/edgewell-sales-genie/catalog/cremo-cooling-shave-cream",
    price: 8,
    originalPrice: 9,
    currency: "USD",
    skinTypes: ["normal", "sensitive"],
    concerns: ["premium grooming", "trade-up", "performance", "bundle"],
    preferences: ["target", "drug", "premium", "men's grooming", "buyer pitch"],
    finish: "natural",
    keyIngredient: "Cooling menthol formula",
    keyBenefits: ["Premium grooming cue", "Performance-led shave prep", "Trade-up opportunity"],
    competitivePositioning: "Wins when the retailer wants a more elevated grooming shelf with stronger specialty cues than basic prep.",
    retailerContext: ["Target", "Drug", "Mass"],
    bundleIdeas: ["Pair with Hydro Sensitive 5 for a premium shave set", "Use in Father’s Day grooming gift displays"],
    talkingPoints: ["Elevates the shelf beyond basic shave prep", "Supports premium men’s grooming storytelling", "Useful as a giftable add-on"],
    objectionHandling: ["If the buyer worries about premium velocity, show it as the trade-up layer rather than the core prep SKU", "If space is constrained, pitch limited seasonal placement with Hydro"],
    seasonality: ["Father's Day", "Holiday gifting", "Everyday grooming"],
    suggestedPitch: "Cremo Cooling Shave Cream gives the razor aisle a more premium grooming upgrade without changing the core architecture.",
    badges: ["Premium Grooming", "Giftable"],
    tags: ["Men's grooming", "Trade-up", "Shave prep"],
    rating: 4.4,
    reviewCount: 1266,
  },
  {
    id: "bulldog-original-face-wash",
    productName: "Original Face Wash",
    brand: "Bulldog",
    category: "Grooming",
    subcategory: "Face Wash",
    description: "Accessible men’s facial care item that rounds out the grooming shelf with a straightforward regimen story.",
    imageUrl: "https://placehold.co/600x600/f1efe7/5f5432.png?text=Bulldog+Original+Face+Wash",
    productUrl: "https://example.com/edgewell-sales-genie/catalog/bulldog-original-face-wash",
    price: 7,
    originalPrice: 8,
    currency: "USD",
    skinTypes: ["normal", "combination", "sensitive"],
    concerns: ["men's grooming", "routine building", "bundle", "everyday core"],
    preferences: ["target", "drug", "mass", "routine", "value-premium"],
    finish: "natural",
    keyIngredient: "Aloe vera and camelina oil",
    keyBenefits: ["Simple regimen entry point", "Broad male shopper appeal", "Useful cross-category bundle piece"],
    competitivePositioning: "Wins by providing a straightforward, approachable grooming step that helps retailers build a fuller men’s care regimen.",
    retailerContext: ["Target", "Drug", "Mass"],
    bundleIdeas: ["Bundle with Schick Hydro and Edge shave prep", "Use in new-year grooming reset sets"],
    talkingPoints: ["Helps move from shave-only to routine-based grooming", "Approachable item for broader shopper adoption", "Supports cross-merchandising in men’s care"],
    objectionHandling: ["If the buyer questions incrementality, show how it expands the basket beyond razors", "If assortment is tight, pitch it as the routine-builder for a focused men’s set"],
    seasonality: ["New Year reset", "Father's Day", "Holiday gifting"],
    suggestedPitch: "Bulldog Original Face Wash helps sellers move the conversation from single-item shaving to everyday men’s grooming routines.",
    badges: ["Routine Builder", "Men's Care"],
    tags: ["Grooming", "Routine", "Cross-sell"],
    rating: 4.3,
    reviewCount: 1132,
  },
  {
    id: "jack-black-double-duty-spf20",
    productName: "Double-Duty Face Moisturizer SPF 20",
    brand: "Jack Black",
    category: "Grooming",
    subcategory: "Moisturizer",
    description: "Prestige-leaning men’s grooming step that helps premium accounts tell a fuller regimen and gifting story.",
    imageUrl: "https://placehold.co/600x600/e6edf5/3f566f.png?text=Jack+Black+Double-Duty+SPF+20",
    productUrl: "https://example.com/edgewell-sales-genie/catalog/jack-black-double-duty-spf20",
    price: 18,
    originalPrice: 20,
    currency: "USD",
    skinTypes: ["normal", "dry", "sensitive"],
    concerns: ["premium grooming", "giftable", "spf", "trade-up", "buyer pitch"],
    preferences: ["target", "specialty", "premium", "gifting", "regimen"],
    finish: "dewy",
    keyIngredient: "Lightweight SPF moisturizer",
    keyBenefits: ["Prestige cue", "Daily-use regimen step", "Giftable premium item"],
    competitivePositioning: "Wins when the account needs a premium men’s care step that adds regimen credibility and better gifting economics.",
    retailerContext: ["Target", "Specialty", "Department"],
    bundleIdeas: ["Pair with Bulldog or Cremo in premium grooming sets", "Use for Father’s Day and holiday gifting towers"],
    talkingPoints: ["Adds premium credibility to men’s care", "Works for gifting and regimen-building", "Supports a broader good-better-best ladder"],
    objectionHandling: ["If price is the concern, frame it as the premium capstone rather than the everyday entry point", "If the buyer wants simpler sets, position it only in premium or seasonal doors"],
    seasonality: ["Father's Day", "Holiday gifting", "Travel"],
    suggestedPitch: "Jack Black Double-Duty gives premium accounts a polished men’s regimen item with strong gifting upside.",
    badges: ["Premium Capstone", "Giftable"],
    tags: ["Premium grooming", "SPF", "Gift set"],
    rating: 4.5,
    reviewCount: 887,
  },
];
